AI_NEWS_FETCHED_AT = "2026-05-10"

AI_ARTICLES = [
    {
        "rank": 1,
"title": "Claude Mythos 因网络攻击被限",
        "source": "TechRepublic",
        "category": "大模型",
"summary": "英国 AISI 确认 Mythos 在 32 步企业网络渗透测试中 3/10 次成功，成为首个因「太危险」而被限制公开的模型。",
"detail": "美国白宫考虑对前沿模型实施 FDA 式安全审查。印度 SEBI 紧急成立网络安全工作组。NSA 据传已在试用 Mythos Preview。",
        "url": "https://www.techrepublic.com/article/ai-agents-data-breaches-and-workforce-shifts-define-this-week-in-tech/",
        "date": "2026-05-08",
    },
    {
        "rank": 2,
"title": "OpenAI GPT-5.5 全面开放",
        "source": "ID Tech Wire",
        "category": "大模型",
"summary": "与 Anthropic 路线相反，OpenAI 全面开放 GPT-5.5。AISI 测试显示其专家级网络任务完成率 71.4%。",
"detail": "GPT-5.5 在多项基准测试中表现出色，但被标记为比前代模型更容易产生幻觉。前沿网络攻击能力每四个月翻一番。",
        "url": "https://idtechwire.com/ai-update-directionally-very-bad/",
        "date": "2026-05-09",
    },
    {
        "rank": 3,
"title": "Anthropic 租下 SpaceX 超算",
        "source": "TechRepublic",
        "category": "硬件",
"summary": "Anthropic 租下 SpaceX 旗下 300MW 级超算中心，配备 22 万+ NVIDIA GPU，Claude Code 限制翻倍。",
"detail": "Colossus 1 位于田纳西州孟菲斯，属于马斯克旗下 SpaceX。这笔交易引发利益冲突讨论——马斯克同时拥有竞品 xAI，却为 Anthropic 提供算力基础设施。",
        "url": "https://www.techrepublic.com/article/ai-power-plays-security-breaches-and-industry-shifts-define-the-week-in-tech/",
        "date": "2026-05-08",
    },
    {
        "rank": 4,
"title": "NVIDIA 六连跌，巨头自研芯片威胁加剧",
        "source": "LA Times",
        "category": "硬件",
"summary": "NVIDIA 股价六天跌 9%。Amazon Trainium 芯片获 2250 亿美元订单承诺，Anthropic 计划投入 2000 亿美元购买 Google TPU。",
"detail": "尽管 NVIDIA 仍占据 86% 市场份额，Meta、Alphabet、Amazon 等科技巨头正加速部署自研 AI 芯片。分析师认为竞争护城河正在收窄。",
        "url": "https://www.latimes.com/business/story/2026-05-06/nvidia-faces-its-biggest-threat-yet-as-tech-giants-build-their-own-ai-chips",
        "date": "2026-05-06",
    },
    {
        "rank": 5,
"title": "五角大楼宣布不依赖单一 AI 供应商",
        "source": "TechRepublic",
        "category": "政策",
"summary": "五角大楼与 8 家 AI 开发商签署协议（排除 Anthropic），正式宣告多元化 AI 供应链战略。",
"detail": "此前 Anthropic 因拒绝军事合作条款被国防部列入黑名单。五角大楼称将永远不再依赖单一供应商，并与 Microsoft、AWS、NVIDIA、Oracle 等签署国防网络部署协议。",
        "url": "https://www.techrepublic.com/article/ai-power-plays-security-breaches-and-industry-shifts-define-the-week-in-tech/",
        "date": "2026-05-07",
    },
    {
        "rank": 6,
"title": "哈佛：AI 急诊诊断超越人类医生",
        "source": "Harvard / MIT Sloan",
        "category": "AI 应用",
"summary": "OpenAI o1-preview 在真实急诊病例诊断中准确率达 67.1%，人类医生为 50-55%。",
"detail": "研究使用真实患者病历而非标准化测试题。AI 在鉴别诊断完整性上表现突出，但研究人员强调目前仍不适合临床独立使用。",
        "url": "https://www.mitsloanme.com/article/ai-dispatch-1-7-may-2026/",
        "date": "2026-05-07",
    },
    {
        "rank": 7,
"title": "欧盟简化 AI 法案，高风险执法推迟",
        "source": "EU / TechRepublic",
        "category": "政策",
"summary": "欧盟将高风险 AI 执法推迟至 2027 年 12 月，AI 生成内容水印要求提前至 2026 年底。",
"detail": "新规同时引入全欧盟范围的 AI 生成非自愿亲密内容禁令。业界认为简化后的法案更务实，但批评者担心执法延期留下监管真空。",
        "url": "https://www.techrepublic.com/article/ai-power-plays-security-breaches-and-industry-shifts-define-the-week-in-tech/",
        "date": "2026-05-06",
    },
    {
        "rank": 8,
"title": "Google 密测新 Agent Remy",
        "source": "TechRepublic",
        "category": "AI 应用",
"summary": "Remy 是 Gemini 内部的行动型 AI 代理，能执行超越聊天的实际操作，取代 Project Mariner。",
"detail": "预计在 5 月 19 日 Google I/O 大会上正式发布。同期 Android 17 Beta 揭示了 Motion Assist、原生应用锁和多任务改进等功能。",
        "url": "https://www.techrepublic.com/article/ai-agents-data-breaches-and-workforce-shifts-define-this-week-in-tech/",
        "date": "2026-05-06",
    },
    {
        "rank": 9,
"title": "中国四实验室 12 天集中发开源模型",
        "source": "State of AI / O'Reilly",
        "category": "开源",
"summary": "智谱 GLM-5.1、MiniMax M2.7、月之暗面 Kimi K2.6、DeepSeek V4 先后开源，推理成本仅 Claude Opus 的 1/3。",
"detail": "四个模型在代理式编程任务上接近同一能力上限，推理成本大幅低于美国竞品。DeepSeek 据报道正进行首次外部融资，估值约 450 亿美元。",
        "url": "https://www.oreilly.com/radar/radar-trends-to-watch-may-2026/",
        "date": "2026-05-05",
    },
    {
        "rank": 10,
"title": "微软-OpenAI 重组，结束排他协议",
        "source": "State of AI",
        "category": "政策",
"summary": "微软与 OpenAI 的 2019 年排他协议终止，OpenAI 可从 Oracle、CoreWeave 多渠道获取算力。",
"detail": "AGI 退出条款被细化的能力门槛取代。微软现通过 Azure Foundry 提供所有前沿模型，包括 Anthropic Opus 4.7。双方关系从排他走向竞合。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-05",
    },
    {
        "rank": 11,
"title": "OpenAI 完成 1220 亿美元融资",
        "source": "State of AI",
        "category": "AI 应用",
"summary": "史上最大私募融资，Q1 完成。Anthropic 据报月底启动新一轮 500 亿美元融资，估值约 9000 亿美元。",
"detail": "两家 AI 巨头的估值竞赛进入白热化。Anthropic 同期获得 Google 追加的 400 亿美元投资。SpaceX 以 600 亿美元估值买下 Cursor 的收购期权。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-05",
    },
    {
        "rank": 12,
"title": "白宫考虑 FDA 式 AI 安全审批",
        "source": "O'Reilly Radar",
        "category": "政策",
"summary": "白宫起草行政令，要求 FDA 式预部署安全审查。Commerce Department 已获得多家 AI 公司自愿评估协议。",
"detail": "此举被视为 AI 监管从自愿走向强制的转折点。微软、Google、xAI 和 OpenAI 已签署自愿预部署评估，Anthropic 的立场尚未明确。",
        "url": "https://www.oreilly.com/radar/radar-trends-to-watch-may-2026/",
        "date": "2026-05-05",
    },
    {
        "rank": 13,
"title": "Anthropic 联手华尔街 15 亿",
        "source": "State of AI",
        "category": "AI 应用",
"summary": "Anthropic 与 Blackstone、Hellman & Friedman、高盛成立合资公司，向中型企业推广 Claude。",
"detail": "OpenAI 同期与 TPG 和 Bain Capital 成立 100 亿美元「部署公司」。AI 从模型之争进入落地之争，华尔街资本深度参与。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-04",
    },
    {
        "rank": 14,
"title": "AI 科学家不会科学推理",
        "source": "O'Reilly Radar",
        "category": "研究",
"summary": "研究发现 AI 研究代理在 68% 的实验中忽略了证据，仅 26% 的案例中出现反驳驱动的信念修正。",
"detail": "这项大规模研究追踪了 25,000 次 AI Agent 科学实验运行。AI 倾向于确认已有假设而非质疑它，真正的科学推理能力仍远未实现。",
        "url": "https://www.oreilly.com/radar/radar-trends-to-watch-may-2026/",
        "date": "2026-05-04",
    },
    {
        "rank": 15,
"title": "通用机器人基础模型 π0.7 发布",
        "source": "State of AI",
        "category": "研究",
"summary": "π0.7 模型实现跨形态零样本迁移，在浓缩咖啡和洗衣任务上匹敌甚至超越 RL 微调专家。",
"detail": "这是首个能在从未见过的机器人形态上直接运行的通用操控模型，标志着机器人基础模型的 ChatGPT 时刻即将到来。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-03",
    },
    {
        "rank": 16,
"title": "ML-Master 2.0 突破 MLE-Bench",
        "source": "O'Reilly Radar",
        "category": "研究",
"summary": "首个突破 50% 奖牌率的机器学习 Agent，采用层级化认知缓存架构，预算控制在 24 小时内。",
"detail": "这是 AI Agent 首次在 MLE-Bench（Kaggle 风格竞赛基准）上实现如此高的完成率。架构创新在于将长期规划和短期执行分层处理，模拟人类的认知层级。",
        "url": "https://www.oreilly.com/radar/radar-trends-to-watch-may-2026/",
        "date": "2026-05-03",
    },
    {
        "rank": 17,
"title": "Cohere 与 Aleph Alpha 合并",
        "source": "State of AI",
        "category": "AI 应用",
"summary": "两家公司合并以创建美国-中国之外的 AI 替代方案，专注欧洲和新兴市场的数据主权需求。",
"detail": "合并后的实体将总部设在多伦多和柏林，主打企业级、合规优先、本地化部署的 AI 解决方案。这是 AI 地缘政治分化的最新信号。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-03",
    },
    {
        "rank": 18,
"title": "欧洲 AI 公司获史上最大 11 亿种子轮",
        "source": "State of AI",
        "category": "AI 应用",
"summary": "欧洲 AI 初创以 51 亿美元估值完成 11 亿美元种子轮，创欧洲种子轮融资纪录。",
"detail": "该公司专注于构建 AI 推理基础设施，总部位于伦敦。巨额种子轮反映了市场对 AI 基础设施层投资的极度乐观预期。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-02",
    },
    {
        "rank": 19,
"title": "Cursor 3：Agent 成主界面",
        "source": "State of AI",
        "category": "AI 应用",
"summary": "Cursor 3 重新定义 AI 编程体验——不再是编辑器加 AI，而是 AI Agent 加编辑器。",
"detail": "新版本将 Agent 通道置于前台，开发者通过自然语言描述目标，Agent 自主规划、编码和测试。IDE 本身退化为 Agent 的执行窗口。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-02",
    },
    {
        "rank": 20,
"title": "好莱坞：AI 表演需支付同等报酬",
        "source": "TechRepublic",
        "category": "政策",
"summary": "好莱坞演员工会新协议要求 AI 生成的表演必须获得演员知情同意并支付人类同等报酬。",
"detail": "此举从根本上削弱了用 AI 替代演员的经济激励。同时金球奖和奥斯卡均裁定 AI 生成演员无获奖资格，AI 增强（去衰老等）仍被允许。",
        "url": "https://www.techrepublic.com/article/ai-agents-data-breaches-and-workforce-shifts-define-this-week-in-tech/",
        "date": "2026-05-02",
    },
    {
        "rank": 21,
"title": "NASA 用 AI 发现 15 颗系外行星",
        "source": "MIT Sloan AI Dispatch",
        "category": "研究",
"summary": "NASA 科学家用 AI 分析 TESS 望远镜数据，一次性确认 15 颗新系外行星，其中 3 颗位于宜居带。",
"detail": "AI 模型在信号识别上比传统方法快 100 倍。这次发现展示了 AI 在天文学数据处理中的巨大潜力，未来有望改变我们寻找地外生命的方式。",
        "url": "https://www.mitsloanme.com/article/ai-dispatch-1-7-may-2026/",
        "date": "2026-05-06",
    },
    {
        "rank": 22,
"title": "Apple 误导 AI 广告赔 2.5 亿",
        "source": "TechRepublic",
        "category": "AI 应用",
"summary": "Apple 因 iPhone 16 发布时对 Apple Intelligence Siri 功能的虚假宣传支付 2.5 亿美元集体诉讼和解金。",
"detail": "宣传中承诺的 AI 功能在发布时并未实现，被消费者集体起诉。这是迄今最大的 AI 产品营销误导案，对行业 AI 宣传合规有警示意义。",
        "url": "https://www.techrepublic.com/article/ai-agents-data-breaches-and-workforce-shifts-define-this-week-in-tech/",
        "date": "2026-05-05",
    },
    {
        "rank": 23,
"title": "DeepSeek 首轮外部融资 450 亿",
        "source": "State of AI",
        "category": "大模型",
"summary": "中国大模型独角兽 DeepSeek 启动首轮外部融资，国家集成电路产业基金领投。",
"detail": "这是 DeepSeek 自成立以来首次引入外部资本。其 V4 模型在推理成本仅为 OpenAI 旧模型 1/3 的情况下达到了接近的性能水平。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-04",
    },
    {
        "rank": 24,
"title": "CISA 发布首份 Agentic AI 指南",
        "source": "O'Reilly Radar",
        "category": "政策",
"summary": "美国网络安全局建议 Agentic AI 先在低风险环境试点，避免授予宽泛的数据访问权限。",
"detail": "指南强调 Agent 的自主决策特性带来新的攻击面：提示注入、工具滥用、权限升级和不可预测的连锁反应。业界普遍视为后续强制标准的铺垫。",
        "url": "https://www.oreilly.com/radar/radar-trends-to-watch-may-2026/",
        "date": "2026-05-04",
    },
    {
        "rank": 25,
"title": "KellyBench 测试：AI 金融决策全败",
        "source": "O'Reilly Radar",
        "category": "研究",
"summary": "38 周逆向投注模拟中，所有前沿 AI 模型均亏损。最佳表现者仅得 32.6% 收益率。",
"detail": "KellyBench 测试 AI 在高度不确定和对抗性环境下的决策能力。结果表明当前 AI 在金融博弈中远不如人类专家，过度自信是主要失败原因。",
        "url": "https://www.oreilly.com/radar/radar-trends-to-watch-may-2026/",
        "date": "2026-05-03",
    },
    {
        "rank": 26,
"title": "AI 真实网购能力仅 33.3%",
        "source": "O'Reilly Radar",
        "category": "研究",
"summary": "153 项真实网页任务（购物、订票、填报）中，最强模型得分仅 33.3%。",
"detail": "测试涵盖了购买商品、预订酒店、填写申请表等日常网络操作。AI 在处理验证码、理解复杂表单逻辑和异常流程处理上表现糟糕。",
        "url": "https://www.oreilly.com/radar/radar-trends-to-watch-may-2026/",
        "date": "2026-05-03",
    },
    {
        "rank": 27,
"title": "Coinbase 裁 700 人转 AI 原生",
        "source": "TechRepublic",
        "category": "AI 应用",
"summary": "Coinbase 裁减 14% 员工以成为 AI 原生企业。同期 Meta 计划裁员 8000 人转投 AI 基础设施。",
"detail": "大型科技公司正加速用 AI 替代传统岗位。中国法院近期裁定企业不得仅因 AI 可完成员工工作而解雇——这一判决可能影响全球劳动法走向。",
        "url": "https://www.techrepublic.com/article/ai-agents-data-breaches-and-workforce-shifts-define-this-week-in-tech/",
        "date": "2026-05-03",
    },
    {
        "rank": 28,
"title": "ElevenLabs 营收突破 5 亿美元",
        "source": "State of AI",
        "category": "AI 应用",
"summary": "AI 语音合成公司 ElevenLabs 成为商业上最成功的纯 AI 公司之一，ARR 超 5 亿美元。",
"detail": "从 AI 语音克隆起家，现已扩展到配音、有声书、实时翻译和游戏角色语音。其成功模式被视为 AI 原生 SaaS 的标杆。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-02",
    },
    {
        "rank": 29,
"title": "美国推动 AI 数据中心暂停建设法案",
        "source": "O'Reilly Radar",
        "category": "政策",
"summary": "11 个州提出限制 AI 数据中心建设的法案，参议员 Sanders 和 Ocasio-Cortez 推动联邦级暂停令。",
"detail": "AI 数据中心的能源消耗和环境影响引发社会反弹。反对者称数据中心将推高电力成本、挤占水资源并破坏社区环境。行业则警告暂停将损害竞争力。",
        "url": "https://www.oreilly.com/radar/radar-trends-to-watch-may-2026/",
        "date": "2026-05-02",
    },
    {
        "rank": 30,
"title": "波浪能 AI 推理公司获 1.4 亿融资",
        "source": "State of AI",
        "category": "硬件",
"summary": "Panthalassa 完成 1.4 亿美元 B 轮，用海洋波浪能驱动海上 AI 推理数据中心。",
"detail": "该公司将 AI 推理服务器部署在浮动平台上，利用波浪能发电并借助海水冷却，号称可实现零碳推理。这是 AI 基础设施去中心化和绿色化的前沿探索。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-02",
    },
    {
        "rank": 31,
"title": "Claude Agent 误删生产数据库",
        "source": "TechRepublic",
        "category": "AI 应用",
"summary": "某公司 Claude Opus 4.6 Agent 因误解指令删除了生产数据库和所有备份。",
"detail": "事件引发 AI Agent 安全边界讨论。CISA 指南建议 Agent 永远不应直接访问生产环境，必须通过人类审批的中间层。这起事故成为 Agentic AI 风险管理的典型案例。",
        "url": "https://www.techrepublic.com/article/ai-power-plays-security-breaches-and-industry-shifts-define-the-week-in-tech/",
        "date": "2026-05-02",
    },
    {
        "rank": 32,
"title": "OpenAI 以 AI 科学家为新北极星",
        "source": "State of AI",
        "category": "研究",
"summary": "OpenAI 告诉 MIT Technology Review，能自主提出假设并实验验证的 AI 科学家是其新北极星。",
"detail": "此举标志着 OpenAI 从通用对话 AI 向科学发现 AI 的战略转型。同时其 ChatGPT Futures 学员项目展示了 26 名学生用 AI 完成天文制图、灾害救援和濒危语言保护等任务。",
        "url": "https://press.airstreet.com/p/state-of-ai-may-2026",
        "date": "2026-05-01",
    },
]
