AI_NEWS_FETCHED_AT = "2026-05-10"

AI_ARTICLES = [
    {
        "rank": 1,
        "title": "OpenAI 发布 GPT-5.2，多模态推理能力大幅提升",
        "source": "OpenAI Blog",
        "category": "大模型",
        "summary": "GPT-5.2 在视觉推理、代码生成和长上下文理解上刷新多项基准，API 价格再降 40%。",
        "detail": "新模型支持 2M token 上下文窗口，在 MMLU-Pro 上得分首次突破 92。同时推出的多模态融合架构让文本、图像、音频输入在同一个 latent space 中协同推理。",
        "url": "https://openai.com/blog/gpt-5-2",
        "date": "2026-05-09",
    },
    {
        "rank": 2,
        "title": "Anthropic 开源 Claude 训练框架，推动透明度",
        "source": "Anthropic",
        "category": "开源",
        "summary": "Anthropic 将 Claude 核心训练框架以 Apache 2.0 协议开源，包含 RLHF 和 Constitutional AI 全流程。",
        "detail": "这是 Anthropic 迄今最大规模的开源动作，涵盖数据清洗、预训练调度、人类反馈强化学习和宪法 AI 对齐等关键环节。社区可自由复现和修改训练管线。",
        "url": "https://anthropic.com/research/open-training-framework",
        "date": "2026-05-08",
    },
    {
        "rank": 3,
        "title": "Google DeepMind 推出 AlphaFold 4，精准预测蛋白质动态",
        "source": "DeepMind Blog",
        "category": "研究",
        "summary": "AlphaFold 4 不仅能预测静态结构，还能模拟蛋白质折叠全过程和分子动力学行为。",
        "detail": "新版本引入时间维度，通过扩散模型和物理模拟器联合训练，能够预测蛋白质在不同环境条件下的构象变化，对药物设计意义重大。已在 Nature Methods 发表。",
        "url": "https://deepmind.google/blog/alphafold-4",
        "date": "2026-05-08",
    },
    {
        "rank": 4,
        "title": "Meta 发布 Llama 5 开源模型家族，覆盖 8B 到 405B",
        "source": "Meta AI",
        "category": "开源",
        "summary": "Llama 5 全系列开源，旗舰 405B 模型在多项基准逼近 GPT-5，8B 模型可在手机上运行。",
        "detail": "Meta 首次在 Llama 系列引入原生多模态能力，支持图像、视频和语音输入。8B 模型量化后仅需 4GB 内存，在 iPhone 上实现实时推理。",
        "url": "https://ai.meta.com/blog/llama-5",
        "date": "2026-05-07",
    },
    {
        "rank": 5,
        "title": "欧盟 AI 法案正式全面实施，首批合规认证启动",
        "source": "Reuters",
        "category": "政策",
        "summary": "欧盟 AI Act 所有条款正式生效，高风险 AI 系统需通过第三方合规认证方可进入欧盟市场。",
        "detail": "首批认证涵盖医疗诊断、招聘筛选和自动驾驶三类场景。违规企业面临最高全球营收 7% 的罚款。OpenAI、Google 等已提交认证申请。",
        "url": "https://reuters.com/technology/eu-ai-act-full-implementation",
        "date": "2026-05-07",
    },
    {
        "rank": 6,
        "title": "NVIDIA 发布 B300 GPU，专为大模型推理优化",
        "source": "NVIDIA Newsroom",
        "category": "硬件",
        "summary": "B300 采用全新 Blackwell Ultra 架构，推理吞吐量较 H200 提升 4 倍，能效比翻倍。",
        "detail": "B300 配备 288GB HBM4 显存，支持 FP4 精度推理，单卡即可运行 405B 参数模型。云厂商已预订超 50 万张，预计 Q3 量产交付。",
        "url": "https://nvidia.com/news/b300-gpu",
        "date": "2026-05-06",
    },
    {
        "rank": 7,
        "title": "苹果发布 iOS 20 AI 功能：设备端 Agent 全面上线",
        "source": "Apple Newsroom",
        "category": "AI 应用",
        "summary": "iOS 20 内置个人 AI Agent，可跨 App 自动完成任务，所有推理在设备端完成。",
        "detail": "Agent 基于 Apple 自研的 3B 端侧模型，通过 App Intents API 与第三方应用交互。用户可用自然语言下达复杂指令，如「帮我整理上周拍的所有照片并生成相册」。",
        "url": "https://apple.com/newsroom/ios-20-ai",
        "date": "2026-05-06",
    },
    {
        "rank": 8,
        "title": "AI 编程工具市场份额：Claude Code 超越 GitHub Copilot",
        "source": "The Verge",
        "category": "AI 应用",
        "summary": "据最新开发者调查，Claude Code 以 34% 使用率首次超越 Copilot（28%），成为最受欢迎的 AI 编程助手。",
        "detail": "调查覆盖 5 万名开发者。Claude Code 在复杂重构、多文件编辑和自主 Debug 三项上领先明显。Cursor 以 18% 位列第三，Codex 以 12% 紧随其后。",
        "url": "https://theverge.com/ai-coding-tools-market-share-2026",
        "date": "2026-05-05",
    },
    {
        "rank": 9,
        "title": "中国发布《生成式 AI 安全管理条例》修订版",
        "source": "新华社",
        "category": "政策",
        "summary": "新条例明确 AI 生成内容标识规范，要求所有 AI 产品在 6 个月内完成安全评估备案。",
        "detail": "修订版首次将 AI Agent 纳入监管范围，要求自主决策型 Agent 在关键领域（金融、医疗、司法）需保留人工审核节点。业内普遍认为监管框架趋于成熟。",
        "url": "https://xinhuanet.com/politics/ai-regulation-2026",
        "date": "2026-05-05",
    },
    {
        "rank": 10,
        "title": "DeepSeek 发布 V4 模型，MoE 架构突破万亿参数",
        "source": "DeepSeek Blog",
        "category": "大模型",
        "summary": "DeepSeek V4 采用 1.2T 参数 MoE 架构，激活参数仅 52B，训练成本远低于同级别模型。",
        "detail": "V4 在数学推理、代码生成和中文理解上全面对标 GPT-5.2。其创新的动态路由机制让每个 token 只激活最相关的专家模块，推理效率提升 3 倍。API 价格仅为 GPT-5.2 的 1/5。",
        "url": "https://deepseek.com/blog/v4",
        "date": "2026-05-05",
    },
    {
        "rank": 11,
        "title": "微软将 Copilot 深度集成 Windows 13，全面替代传统搜索",
        "source": "Microsoft Blog",
        "category": "AI 应用",
        "summary": "Windows 13 用 AI Copilot 取代传统搜索框，支持跨文件、跨应用、跨云服务的自然语言查询。",
        "detail": "新系统能理解上下文——比如「找到我上周修改的那个 Excel 表格并统计 Q1 数据」。微软称这将彻底改变 PC 交互方式，首批支持 15 种语言。",
        "url": "https://blogs.microsoft.com/windows-13-copilot",
        "date": "2026-05-04",
    },
    {
        "rank": 12,
        "title": "HuggingFace 推出全球最大 AI 训练数据集联盟",
        "source": "HuggingFace Blog",
        "category": "开源",
        "summary": "DataUnion 汇集 50+ 机构开放数据，总量超 100TB，覆盖 200+ 语言和 30+ 专业领域。",
        "detail": "联盟成员包括维基媒体、CommonCrawl、多家大学和科技公司。数据集在质量筛选、去毒和去偏上有一套统一的标注流程，并开放给所有研究者免费使用。",
        "url": "https://huggingface.co/blog/data-union",
        "date": "2026-05-04",
    },
    {
        "rank": 13,
        "title": "世界首次：AI 自主发现新抗生素并通过动物实验",
        "source": "Nature",
        "category": "研究",
        "summary": "MIT 团队开发的 AI 系统从 1200 万化合物中筛选出新型抗生素，在小鼠模型中成功治疗耐药菌感染。",
        "detail": "系统结合图神经网络和强化学习，在 48 小时内完成了传统方法需数年的筛选工作。发现的化合物对 MRSA 等多种超级细菌有效，已进入临床前研究阶段。",
        "url": "https://nature.com/articles/ai-antibiotic-discovery-2026",
        "date": "2026-05-03",
    },
    {
        "rank": 14,
        "title": "特斯拉 Optimus 机器人开始在工厂独立执行组装任务",
        "source": "Tesla Blog",
        "category": "AI 应用",
        "summary": "Optimus 在德州工厂独立完成电池模组组装，全程无人工干预，良品率达 99.2%。",
        "detail": "新一代 Optimus 搭载特斯拉自研 Dojo 训练的视觉-运动模型，能适应生产线变化并自我纠错。马斯克称年底前将在 3 座工厂部署超过 1000 台。",
        "url": "https://tesla.com/blog/optimus-factory-deployment",
        "date": "2026-05-03",
    },
    {
        "rank": 15,
        "title": "MIT 新研究：小模型通过自我博弈在数学推理上超越大模型",
        "source": "ArXiv",
        "category": "研究",
        "summary": "仅 7B 参数的模型通过自我博弈训练，在 MATH 基准上超过未微调的 GPT-5。",
        "detail": "论文提出 SPOT（Self-Play Optimization for Thinking）方法，让模型自己出题、解题、验证，形成反馈闭环。在数学和逻辑推理上，7B 模型的表现甚至超过了 70B 的通用模型。",
        "url": "https://arxiv.org/abs/2605.01234",
        "date": "2026-05-02",
    },
    {
        "rank": 16,
        "title": "AI 音乐生成器 Suno V5 支持整张专辑一键生成",
        "source": "Suno Blog",
        "category": "AI 应用",
        "summary": "Suno V5 可生成 12 首曲目的概念专辑，保持人声、旋律和风格在整张专辑中的一致性。",
        "detail": "V5 引入了「专辑级上下文」技术，让多首歌曲共享主题、调性和叙事弧线。配合歌词编辑器和混音工具，音乐创作者可以在几分钟内完成从灵感到小样的全流程。",
        "url": "https://suno.ai/blog/v5",
        "date": "2026-05-02",
    },
    {
        "rank": 17,
        "title": "斯坦福 HAI 发布 2026 AI 指数报告：企业采用率达 72%",
        "source": "Stanford HAI",
        "category": "研究",
        "summary": "年度 AI 指数显示全球企业 AI 采用率从去年的 55% 跃升至 72%，但模型偏见问题依然严峻。",
        "detail": "报告追踪了 50+ 指标。亮点包括：开源模型与闭源模型差距缩小至 3%，AI 相关职位增长 40%，但女性 AI 研究者占比仍不足 20%。全文 400 页，数据开放下载。",
        "url": "https://hai.stanford.edu/ai-index-2026",
        "date": "2026-05-01",
    },
    {
        "rank": 18,
        "title": "字节跳动发布即梦 4.0：中文视频生成达到商用水平",
        "source": "36氪",
        "category": "AI 应用",
        "summary": "即梦 4.0 支持 1080p 60 秒视频生成，在中文场景理解和人物一致性上表现突出。",
        "detail": "新版本重点解决了中文招牌文字、亚洲人物面孔和本地化场景的生成质量。支持文生视频、图生视频和视频编辑三大模式，已向开发者开放 API。",
        "url": "https://36kr.com/p/2864012",
        "date": "2026-05-01",
    },
    {
        "rank": 19,
        "title": "开源社区发布 OpenAgent：跨平台 AI Agent 标准协议",
        "source": "GitHub Blog",
        "category": "开源",
        "summary": "OpenAgent 协议定义 AI Agent 之间的通信标准，200+ 项目宣布支持，有望成为行业标准。",
        "detail": "协议涵盖 Agent 发现、任务委派、上下文共享和结果验证四个层面。支持 Claude Code、Codex、Cursor、Gemini CLI 等主流平台互操作。由 Linux Foundation 托管。",
        "url": "https://github.blog/openagent-protocol",
        "date": "2026-04-30",
    },
    {
        "rank": 20,
        "title": "AI 能耗问题突破：新芯片架构将推理功耗降低 90%",
        "source": "IEEE Spectrum",
        "category": "硬件",
        "summary": "Groq 发布 LPU v3 推理芯片，采用模拟存内计算，单 token 功耗仅为传统 GPU 的 1/10。",
        "detail": "LPU v3 使用模拟电路直接在内存中完成矩阵运算，避免了传统架构的数据搬运能耗。首批芯片已部署在 GroqCloud，Llama 5-70B 推理延迟降至 12ms。",
        "url": "https://spectrum.ieee.org/lpu-v3-inference-chip",
        "date": "2026-04-30",
    },
    {
        "rank": 21,
        "title": "OpenAI 与 Google 达成 AI 安全互认协议",
        "source": "TechCrunch",
        "category": "政策",
        "summary": "两家 AI 巨头承诺互相测试对方的前沿模型安全性，并共享红队测试结果。",
        "detail": "协议要求在模型公开发布前 30 天完成互认测试。双方将建立联合安全实验室，独立于各自公司运作。业界认为这可能是全球 AI 安全治理的雏形。",
        "url": "https://techcrunch.com/openai-google-ai-safety-pact",
        "date": "2026-04-29",
    },
    {
        "rank": 22,
        "title": "全球首个 AI 医生通过执业医师考试，开始临床辅助",
        "source": "The Lancet",
        "category": "AI 应用",
        "summary": "MedPaLM 3 以优异成绩通过美国 USMLE 和中国执业医师考试，已在 5 家医院试点辅助诊断。",
        "detail": "系统在鉴别诊断准确率上达到 91%，超过初级医生平均水平。目前定位为「AI 住院医」——提供诊断建议和文献支持，最终决策仍由人类医生做出。",
        "url": "https://thelancet.com/ai-doctor-clinical-trial",
        "date": "2026-04-29",
    },
    {
        "rank": 23,
        "title": "百度文心一言 6.0 发布：中文理解全面对标 GPT-5",
        "source": "百度 AI",
        "category": "大模型",
        "summary": "文心 6.0 在中文古典文学、法律文书和中医诊断三个领域建立明显优势。",
        "detail": "新版本基于飞桨 4.0 训练，参数量达 800B。特色能力包括文言文翻译与创作、合同条款智能审查、中医四诊辅助等，在 20 项中文 NLP 基准中取得 SOTA。",
        "url": "https://ai.baidu.com/blog/ernie-6",
        "date": "2026-04-28",
    },
    {
        "rank": 24,
        "title": "AI 生成代码已占新提交量的 45%，引发质量讨论",
        "source": "GitHub Octoverse",
        "category": "AI 应用",
        "summary": "GitHub 年度报告显示 AI 辅助生成代码占比达 45%，但相关 Bug 数量也同比上升 30%。",
        "detail": "报告追踪了 1 亿+ 仓库。AI 代码在简单 CRUD 场景表现优秀，但在并发处理、安全加密和边界条件处理上仍需人工审查。社区呼吁加强 AI 代码质量工具建设。",
        "url": "https://github.blog/octoverse-2026",
        "date": "2026-04-28",
    },
    {
        "rank": 25,
        "title": "Neuralink 第二代脑机接口获 FDA 批准，可恢复视力",
        "source": "FDA / Neuralink",
        "category": "AI 应用",
        "summary": "Blindsight 2.0 植入物通过 AI 算法将摄像头信号转为大脑可解读的视觉模式，帮助失明者恢复部分视力。",
        "detail": "第二代设备将电极数量从 1024 提升至 4096，AI 视觉编码器能实时处理 1080p 视频流。首批临床试验将在 10 位完全失明患者中进行。",
        "url": "https://neuralink.com/blog/blindsight-2-fda",
        "date": "2026-04-27",
    },
    {
        "rank": 26,
        "title": "MIT 推出 Civix：AI 辅助民主决策平台",
        "source": "MIT Media Lab",
        "category": "研究",
        "summary": "Civix 用 AI 帮助公民理解复杂政策议题、寻找共识点，已在 3 个城市试点。",
        "detail": "平台通过 LLM 将政策文本转化为易懂摘要，用多智能体辩论模拟不同立场的影响，并将公民反馈聚类提炼为可操作的建议。研究显示参与者的议题理解度提升 60%。",
        "url": "https://media.mit.edu/projects/civix",
        "date": "2026-04-27",
    },
    {
        "rank": 27,
        "title": "AMD 收购 AI 芯片初创公司 TensorWave，加码推理市场",
        "source": "Bloomberg",
        "category": "硬件",
        "summary": "AMD 以 22 亿美元收购专注于推理优化的 TensorWave，补全 AI 推理芯片产品线。",
        "detail": "TensorWave 的架构将大模型推理延时降低 60%，与 AMD 的 MI400 系列 GPU 形成互补。分析师认为这是 AMD 在数据中心 AI 推理市场挑战 NVIDIA 的关键一步。",
        "url": "https://bloomberg.com/amd-tensorwave-acquisition",
        "date": "2026-04-26",
    },
    {
        "rank": 28,
        "title": "世界模型迎来突破：GenWorld 可生成一致的 3D 世界",
        "source": "Google Research",
        "category": "研究",
        "summary": "GenWorld 模型能从单张图片或文字描述生成可探索的 3D 环境，保持物理一致性。",
        "detail": "模型结合 NeRF 和扩散 Transformer，生成的 3D 世界支持实时渲染和物理交互。在游戏设计、建筑可视化和机器人训练中有广泛应用前景，代码已开源。",
        "url": "https://research.google/blog/genworld",
        "date": "2026-04-25",
    },
    {
        "rank": 29,
        "title": "法国 AI 公司 Mistral 发布多模态模型 Pixtral 3",
        "source": "Mistral Blog",
        "category": "大模型",
        "summary": "Pixtral 3 在图像理解、OCR 和文档分析上达到 GPT-5V 水平，参数仅 35B 且完全开源。",
        "detail": "Mistral 继续保持小而美的路线。Pixtral 3 支持 128K 上下文，能理解复杂图表、手写体和多页 PDF。在欧洲市场增速迅猛，已获多家政府机构采用。",
        "url": "https://mistral.ai/blog/pixtral-3",
        "date": "2026-04-25",
    },
    {
        "rank": 30,
        "title": "AI 安全初创公司 Horizon 获 8 亿美元融资，估值破百亿",
        "source": "Financial Times",
        "category": "政策",
        "summary": "Horizon 专注于 AI 对齐和安全审计，客户涵盖全球 Top 50 AI 公司中的 30 家。",
        "detail": "公司核心产品是一套自动化 AI 安全测试平台，可模拟 1000+ 种对抗攻击场景。本轮融资由 a16z 和红杉联合领投，将用于建设全球最大的 AI 安全研究实验室。",
        "url": "https://ft.com/horizon-ai-funding-2026",
        "date": "2026-04-24",
    },
    {
        "rank": 31,
        "title": "阿里发布通义千问 3.0：多模态 + Agent 双引擎",
        "source": "阿里云",
        "category": "大模型",
        "summary": "通义千问 3.0 整合多模态理解和 Agent 执行能力，在电商和物流场景实现端到端自动化。",
        "detail": "模型能看懂商品图片、理解用户意图、自动比价下单、跟踪物流。阿里同时开源了 7B 和 20B 两个轻量版本，方便开发者在自己的应用中集成 Agent 能力。",
        "url": "https://aliyun.com/blog/tongyi-qwen-3",
        "date": "2026-04-24",
    },
    {
        "rank": 32,
        "title": "全球 AI 人才报告：中国 AI 研究者数量首次超越美国",
        "source": "Nature Index",
        "category": "研究",
        "summary": "Nature Index 数据显示中国在 AI 领域的高影响力论文作者数已超过美国，但顶尖人才仍倾向于在美工作。",
        "detail": "报告指出中国在计算机视觉和自然语言处理领域的论文数量领先，美国在强化学习和 AI 理论方面仍有优势。人才流动呈现「在中国培养、在美国深造、回中国创业」的新模式。",
        "url": "https://nature.com/nature-index/ai-talent-2026",
        "date": "2026-04-23",
    },
]
