GITHUB_DEMO_FETCHED_AT = "2026-05-10"
GITHUB_DEMO_QUERY = "created:>=2026-02-09 stars:>100 sort:stars-desc"


GITHUB_PROJECTS = [
    {
        "rank": 1,
        "name": "爪码 Claw Code",
        "repo": "ultraworkers/claw-code",
        "stars": 190812,
        "tech": ["Rust", "AI Coding", "CLI"],
        "summary": "一个增长极快的 Rust 智能编码项目，围绕 Codex 风格的开发体验做性能和工具链实验。",
        "detail": "它像一个高速实验场，把编码代理、命令行工作流和 Rust 性能放在一起。适合观察 AI 编程工具如何从提示词走向工程化工具箱。",
        "url": "https://github.com/ultraworkers/claw-code",
        "created_at": "2026-03-31",
    },
    {
        "rank": 2,
        "name": "Garry 的代理工作台",
        "repo": "garrytan/gstack",
        "stars": 92006,
        "tech": ["TypeScript", "Claude Code", "Agent Workflow"],
        "summary": "把 CEO、设计师、工程经理、发布经理等角色整理成一套可复用的 AI 工作流工具。",
        "detail": "项目重点不是单个模型能力，而是把团队角色、文档、发布和 QA 串成一条可操作流程。对个人开发者搭建 AI 工作台很有参考价值。",
        "url": "https://github.com/garrytan/gstack",
        "created_at": "2026-03-11",
    },
    {
        "rank": 3,
        "name": "自动研究员",
        "repo": "karpathy/autoresearch",
        "stars": 79906,
        "tech": ["Python", "AI Agent", "Research Automation"],
        "summary": "让 AI 代理自动运行单 GPU nanochat 训练研究的实验项目。",
        "detail": "它把研究过程拆成可重复的训练、观察和迭代任务。适合关注小规模可复现实验、AI 研究自动化的人。",
        "url": "https://github.com/karpathy/autoresearch",
        "created_at": "2026-03-06",
    },
    {
        "rank": 4,
        "name": "设计规范宝库",
        "repo": "VoltAgent/awesome-design-md",
        "stars": 73922,
        "tech": ["Design.md", "UI Systems", "Agent Design"],
        "summary": "收集流行品牌设计系统风格的 DESIGN.md 文件，让编码代理生成更贴近品牌的 UI。",
        "detail": "它解决的是 AI 写前端时没有视觉约束的问题。把设计系统变成文件后，代理可以按品牌语气、颜色和组件习惯生成页面。",
        "url": "https://github.com/VoltAgent/awesome-design-md",
        "created_at": "2026-03-31",
    },
    {
        "rank": 5,
        "name": "纸夹公司编排器",
        "repo": "paperclipai/paperclip",
        "stars": 63673,
        "tech": ["TypeScript", "AI Orchestration", "Automation"],
        "summary": "面向“零人类公司”的开源 AI 编排系统。",
        "detail": "项目关注多代理协作、任务编排和自动化组织流程。它代表了 AI 从助手走向业务流程执行层的趋势。",
        "url": "https://paperclip.ing",
        "created_at": "2026-03-02",
    },
    {
        "rank": 6,
        "name": "穴居人模式",
        "repo": "JuliusBrussee/caveman",
        "stars": 56861,
        "tech": ["Python", "Claude Code Skill", "Token Optimization"],
        "summary": "通过极简语言压缩 Claude Code 对话 token 的技能项目。",
        "detail": "它很有趣，也很实用：用更少文字保留工程信息密度。适合长会话、代码审查、规划等需要节省上下文的场景。",
        "url": "https://getcaveman.dev/",
        "created_at": "2026-04-04",
    },
    {
        "rank": 7,
        "name": "记忆宫殿",
        "repo": "MemPalace/mempalace",
        "stars": 51705,
        "tech": ["Python", "AI Memory", "Retrieval"],
        "summary": "开源 AI 记忆系统，强调基准表现和免费可用。",
        "detail": "长期记忆是 AI 产品从聊天玩具变成长期助手的关键。这个项目适合跟踪记忆存储、检索和上下文注入的工程路线。",
        "url": "http://mempalaceofficial.com/",
        "created_at": "2026-04-05",
    },
    {
        "rank": 8,
        "name": "精准文本排版引擎",
        "repo": "chenglou/pretext",
        "stars": 46502,
        "tech": ["TypeScript", "Text Layout", "Rendering"],
        "summary": "快速、准确、全面的文本测量与布局工具。",
        "detail": "文本排版是很多创意工具、编辑器和可视化系统的底层能力。它适合用来做 ASCII 艺术、文本游戏、复杂文档布局。",
        "url": "http://chenglou.me/pretext/",
        "created_at": "2026-03-07",
    },
    {
        "rank": 9,
        "name": "代码知识图谱",
        "repo": "safishamsi/graphify",
        "stars": 45290,
        "tech": ["Python", "Knowledge Graph", "Code Intelligence"],
        "summary": "把代码、数据库、脚本、文档、论文、图片和视频转成可查询的知识图谱。",
        "detail": "它试图把项目知识从文件树升级为图谱。对大型代码库理解、架构问答和跨模态资料检索很有价值。",
        "url": "https://graphifylabs.ai/",
        "created_at": "2026-04-03",
    },
    {
        "rank": 10,
        "name": "职业作战系统",
        "repo": "santifer/career-ops",
        "stars": 43695,
        "tech": ["JavaScript", "Go Dashboard", "PDF"],
        "summary": "用 AI 辅助求职流程，包含技能模式、仪表盘、PDF 生成和批处理。",
        "detail": "它把求职看成一个可运营系统：岗位追踪、材料生成、批量处理、进度管理。适合研究 AI 如何进入个人生产力流程。",
        "url": "https://career-ops.org",
        "created_at": "2026-04-04",
    },
    {
        "rank": 11,
        "name": "代理技能库",
        "repo": "addyosmani/agent-skills",
        "stars": 36733,
        "tech": ["Shell", "AI Coding Skills", "Engineering"],
        "summary": "生产级工程技能集合，服务 AI 编码代理。",
        "detail": "这个项目体现了一个新趋势：不只提示模型，而是把工程方法沉淀成可加载技能，让代理按成熟流程工作。",
        "url": "https://github.com/addyosmani/agent-skills",
        "created_at": "2026-02-15",
    },
    {
        "rank": 12,
        "name": "开放设计工坊",
        "repo": "nexu-io/open-design",
        "stars": 34695,
        "tech": ["TypeScript", "Design Systems", "Prototype Export"],
        "summary": "本地优先的开源 Claude Design 替代方案，支持多种设计系统和原型导出。",
        "detail": "它把网页、桌面、移动端原型、幻灯片、图片和视频生成放进同一套沙盒预览流程里，适合设计工程一体化。",
        "url": "https://open-design.ai",
        "created_at": "2026-04-28",
    },
    {
        "rank": 13,
        "name": "万物命令行",
        "repo": "HKUDS/CLI-Anything",
        "stars": 34029,
        "tech": ["Python", "CLI", "Agent Native Software"],
        "summary": "目标是让所有软件变成代理可操作的命令行形态。",
        "detail": "它的方向很直接：如果 AI 代理要真正操作软件，就需要稳定、可组合、可脚本化的 CLI 接口。",
        "url": "https://clianything.cc/",
        "created_at": "2026-03-08",
    },
    {
        "rank": 14,
        "name": "零爪个人助手底座",
        "repo": "zeroclaw-labs/zeroclaw",
        "stars": 31170,
        "tech": ["Rust", "Personal Assistant", "Infrastructure"],
        "summary": "小型、快速、全自主的 AI 个人助手基础设施。",
        "detail": "它强调跨系统部署和可替换组件，适合观察个人 AI 助手如何从聊天窗口变成常驻基础设施。",
        "url": "https://www.zeroclawlabs.ai/",
        "created_at": "2026-02-13",
    },
    {
        "rank": 15,
        "name": "开放 Claude 客户端",
        "repo": "Gitlawb/openclaude",
        "stars": 26214,
        "tech": ["TypeScript", "AI Client", "Cross Platform"],
        "summary": "一个可在多环境运行、可接多种后端的开放 Claude 风格客户端。",
        "detail": "它关注客户端层的自由度：在哪里运行、接什么模型、如何组织对话和工具。适合对 AI 产品壳层感兴趣的人。",
        "url": "https://openclaude.gitlawb.com",
        "created_at": "2026-04-01",
    },
    {
        "rank": 16,
        "name": "Google Workspace 命令行",
        "repo": "googleworkspace/cli",
        "stars": 25958,
        "tech": ["Rust", "Google APIs", "CLI"],
        "summary": "用一个命令行工具操作 Drive、Gmail、Calendar、Sheets、Docs、Chat 和 Admin。",
        "detail": "它把 Workspace 的大量 API 动态构造成 CLI，并包含 AI 代理技能。对企业办公自动化和代理工具接入很关键。",
        "url": "https://developers.google.com/workspace",
        "created_at": "2026-03-02",
    },
    {
        "rank": 17,
        "name": "本机模型适配器",
        "repo": "AlexsJones/llmfit",
        "stars": 25544,
        "tech": ["Rust", "LLM Runtime", "Hardware Matching"],
        "summary": "用一个命令帮你找到适合当前硬件运行的模型和服务商。",
        "detail": "本地模型生态越来越复杂，用户关心的是“我的机器能跑什么”。这个项目把模型选择变成硬件适配问题。",
        "url": "https://github.com/AlexsJones/llmfit",
        "created_at": "2026-02-15",
    },
    {
        "rank": 18,
        "name": "交响乐任务编排",
        "repo": "openai/symphony",
        "stars": 22786,
        "tech": ["Elixir", "Codex Orchestration", "Autonomous Runs"],
        "summary": "OpenAI 开源的 Codex 编排项目，把工作拆成隔离的自主实现运行。",
        "detail": "它的重点是团队如何管理 AI 实现任务，而不是盯着每个代理输出。对未来软件项目管理方式很有代表性。",
        "url": "https://openai.com/index/open-source-codex-orchestration-symphony/",
        "created_at": "2026-02-26",
    },
    {
        "rank": 19,
        "name": "NVIDIA 安全开放爪",
        "repo": "NVIDIA/NemoClaw",
        "stars": 20227,
        "tech": ["TypeScript", "NVIDIA OpenShell", "Managed Inference"],
        "summary": "在 NVIDIA OpenShell 中更安全地运行 OpenClaw，并接入托管推理。",
        "detail": "它体现了大厂对 AI 编码代理安全运行环境的关注：沙盒、推理管理、权限边界会越来越重要。",
        "url": "https://docs.nvidia.com/nemoclaw/latest/",
        "created_at": "2026-03-15",
    },
    {
        "rank": 20,
        "name": "低成本相控阵雷达",
        "repo": "NawfalMotii79/PLFM_RADAR",
        "stars": 19850,
        "tech": ["PLSQL", "Radar", "Hardware"],
        "summary": "开源、低成本的 10.5GHz PLFM 相控阵雷达系统。",
        "detail": "这类项目说明 GitHub 热门不只属于 AI 软件，也会突然出现硬件与工程系统。它适合放在科技频道作为跨界观察样本。",
        "url": "https://github.com/NawfalMotii79/PLFM_RADAR",
        "created_at": "2026-03-08",
    },
    {
        "rank": 21,
        "name": "工程师真功夫",
        "repo": "mattpocock/skills",
        "stars": 67786,
        "tech": ["Shell", "Engineering Skills", "Claude Code"],
        "summary": "TypeScript 大神 Matt Pocock 的 Claude Code 技能包，面向正经工程实践。",
        "detail": "它是 agent-skills 的同门前辈，偏重传统工程流程里的 TypeScript、测试、CI/CD 等实践。两个技能库一横一纵，覆盖了个人到团队的生产力需求。",
        "url": "https://github.com/mattpocock/skills",
        "created_at": "2026-02-03",
    },
    {
        "rank": 22,
        "name": "纳米机器人",
        "repo": "HKUDS/nanobot",
        "stars": 42083,
        "tech": ["Python", "AI Agent", "Lightweight"],
        "summary": "超轻量的个人 AI 代理，一只猫就能驱动。",
        "detail": "它把 AI 代理压缩到极致简单，适合嵌入各种环境。项目名称自带猫猫 buff，在追求极简部署的场景里很受欢迎。",
        "url": "https://github.com/HKUDS/nanobot",
        "created_at": "2026-02-01",
    },
    {
        "rank": 23,
        "name": "OpenClaw 百宝箱",
        "repo": "hesamsheikh/awesome-openclaw-usecases",
        "stars": 30879,
        "tech": ["Markdown", "Community", "Use Cases"],
        "summary": "社区驱动的 OpenClaw 用例合集，覆盖生活与工作场景。",
        "detail": "它像一个不断生长的手册，记录了用户如何用 OpenClaw 自动化日常琐事、处理数据和辅助决策。适合寻找灵感和最佳实践。",
        "url": "https://github.com/hesamsheikh/awesome-openclaw-usecases",
        "created_at": "2026-02-08",
    },
    {
        "rank": 24,
        "name": "迷你爪",
        "repo": "sipeed/picoclaw",
        "stars": 28895,
        "tech": ["Go", "Automation", "Edge"],
        "summary": "极简、高速、随处部署的自动化引擎。",
        "detail": "Go 语言实现，编译后单文件部署，适合边缘设备和资源受限环境。它把自动化的门槛从服务器拉到了树莓派级别。",
        "url": "https://github.com/sipeed/picoclaw",
        "created_at": "2026-02-04",
    },
    {
        "rank": 25,
        "name": "Codex 增强套件",
        "repo": "Yeachan-Heo/oh-my-codex",
        "stars": 28048,
        "tech": ["TypeScript", "Codex Plugin", "Agent Team"],
        "summary": "给 Codex 装上 hooks、代理团队和 HUD 面板。",
        "detail": "它把单个 Codex 变成一支小队——可以挂载钩子、组建代理团、显示可视化面板。对需要复杂编排的开发者来说像开了外挂。",
        "url": "https://github.com/Yeachan-Heo/oh-my-codex",
        "created_at": "2026-02-02",
    },
    {
        "rank": 26,
        "name": "开放命令行枢纽",
        "repo": "jackwener/OpenCLI",
        "stars": 19466,
        "tech": ["JavaScript", "CLI", "AI Native"],
        "summary": "把任何网站和工具变成 CLI 接口。",
        "detail": "它的目标和 CLI-Anything 相似但侧重不同：它是从 Web 端反向生成 CLI，让代理能操作原本没有命令行入口的在线服务。",
        "url": "https://github.com/jackwener/OpenCLI",
        "created_at": "2026-03-14",
    },
    {
        "rank": 27,
        "name": "代理之眼",
        "repo": "Panniantong/Agent-Reach",
        "stars": 19073,
        "tech": ["Python", "Web Scraping", "AI Agent"],
        "summary": "让 AI 代理阅读和搜索整个互联网。",
        "detail": "它给代理装上眼睛——能读 Twitter、Reddit、YouTube、GitHub 等平台内容。适合需要实时互联网感知的研究和情报类任务。",
        "url": "https://github.com/Panniantong/Agent-Reach",
        "created_at": "2026-02-24",
    },
    {
        "rank": 28,
        "name": "女娲思维蒸馏",
        "repo": "alchaincyf/nuwa-skill",
        "stars": 18245,
        "tech": ["Python", "Knowledge Distillation", "AI Agent"],
        "summary": "蒸馏任何人的思维方式——心智模型、决策启发式、表达DNA。",
        "detail": "你下一个想蒸馏的员工，何必是同事。它把思维模式从人迁移到模型，适合研究 AI 如何模仿特定个体的判断和表达风格。",
        "url": "https://github.com/alchaincyf/nuwa-skill",
        "created_at": "2026-04-05",
    },
    {
        "rank": 29,
        "name": "Codex 桥接器",
        "repo": "openai/codex-plugin-cc",
        "stars": 18019,
        "tech": ["JavaScript", "Claude Code", "Codex"],
        "summary": "在 Claude Code 里直接调用 Codex 来审查代码或委派任务。",
        "detail": "OpenAI 官方出品，把两个 AI 编码工具连在一起。Codex 负责任务执行，Claude Code 负责审查和调度，双引擎协作。",
        "url": "https://github.com/openai/codex-plugin-cc",
        "created_at": "2026-03-30",
    },
    {
        "rank": 30,
        "name": "Claude Code 可构建版",
        "repo": "claude-code-best/claude-code",
        "stars": 17903,
        "tech": ["TypeScript", "Claude Code", "DevTools"],
        "summary": "原汁原味可运行、可构建、可调试的 Claude Code 社区版。",
        "detail": "生产级工程化，企业级可靠性。方便开发者深入了解 Claude Code 内部机制，也适合做二次开发和定制。",
        "url": "https://github.com/claude-code-best/claude-code",
        "created_at": "2026-03-31",
    },
]
